version: "2"
services:
  test_local:
    build: .
    depends_on:
      - hub
      - chromeNode
      - firefoxNode
    environment:
      BROWSER: chrome
      HUB_HOST: hub
      PLATFORM: en
      HOST: dawanda.com
      PORT: 4444
    volumes:
     - ./atd_example:/app

  hub:
    image: selenium/hub:3.7.1-argon
    ports:
      - "4444"

  chromeNode:
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      DBUS_SESSION_BUS_ADDRESS: /dev/null
    ports:
    - 5900
    image: selenium/node-chrome:3.7.1-argon

  firefoxNode:
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      DBUS_SESSION_BUS_ADDRESS: /dev/null
    ports:
    - 5900
    image: selenium/node-firefox:3.7.1-argon
